apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: hello-world-ingress
  namespace: blog
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  tls:
  - hosts:
      - ghdevopstechblog.hopto.org
    secretName: ghdevopstechblog.hopto.org
  rules:
  - host: ghdevopstechblog.hopto.org
    http:
      paths:
      - path: /
        backend:
          serviceName: blog
          servicePort: 80