apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: hello-world-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 16m
spec:
  tls:
  - hosts:
      - ghdevopstechblog.hopto.org
    secretName: ghdevopstechblog.hopto.org
  rules:
  - host: ghdevopstechblog.hopto.org
    http:
      paths:
      - path: /
        backend:
          serviceName: blog
          servicePort: 2368
